app_name: reviews-backend
replica_count: 1
port: 80
image: 
  repo: 505789305843.dkr.ecr.us-east-1.amazonaws.com/reviews-backend
  tag: "0.1"
serviceType: LoadBalancer
resources: {}
ingress:
  enabled: false